# Generated by Django 4.2.5 on 2023-10-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address_1',
            new_name='company_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_address_2',
        ),
    ]
