# Generated by Django 4.2.5 on 2023-10-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_company_address_1_company_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_address',
        ),
    ]
