# Generated by Django 4.2.5 on 2023-10-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_company_company_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
